### DISCUSSION TITLE
Adding todo for battery + sensor needed

### DISCUSSION THREAD

**Discussion by skank01** [andrew-codechimp/HA-Battery-Notes#1995] [Q&A]
Instead of getting a persistent notification, i'm trying to add it to my todo list for each battery below threshold.
I tried this, but get error:
[code=yaml]
sequence:
            - service: todo.add_item
              metadata: {}
              data:
                item: {{ trigger.event.data.device_name }} Batterij laag. Nodig {{
                trigger.event.data.battery_quantity }}× {{
                trigger.event.data.battery_type }}
              target:
                entity_id: todo.to_do      
[/code]

Anyone succeeded in this?
I also want a sensor that counts the batteries that need a charge or change..
How can i do that?
Reason for this is, that i want a button in my dashboard, that only shows up, if the count is not 0 , so its present when i need to do actions.

Thx for the help here.

**Comment by andrew-codechimp** [comment]
Here's a complete automation example I've just knocked up

```
alias: Battery Low Todo
description: Battery Low Todo
trigger:
  - platform: event
    event_type: battery_notes_battery_threshold
    event_data:
      battery_low: true
    alias: Battery went low
condition: []
action:
  - action: todo.add_item
    metadata: {}
    data:
      item: |
        {{ trigger.event.data.device_name }} Battery Low
      description: >
        The device has a battery level of {{ trigger.event.data.battery_level
        }}% {{ '\n' -}} You need {{ trigger.event.data.battery_quantity }}× {{
        trigger.event.data.battery_type }}
    target:
      entity_id: todo.test
mode: queued
```

To test it you can use the Events tab in developer tools like this
![CleanShot 2024-08-21 at 19 24 23@2x](https://github.com/user-attachments/assets/3f0f25ff-e85e-4e47-bab9-baabc4b8fd9e)
