### DISCUSSION TITLE
Use BinarySensorDeviceClass.BATTERY to create "*_battery_plus_low"

### DISCUSSION THREAD

**Discussion by peterwup** [andrew-codechimp/HA-Battery-Notes#2593] [Ideas]
Hi, 
I have many devices which only have an "BinarySensorDeviceClass.BATTERY" entity. 
For such devices the entity "*_battery_plus_low" is not created. 
Disadvantage: If I want to filter I need to filter for two entities. 
I can change this by adding a template to each battery like: 
"{{states('binary_sensor.garagentorpos_low_battery')}}"
I have to do this for every single device, not per device type. 
Wouldn't it be possible to this automatic like for the sensor battery ?

**Comment by andrew-codechimp** [comment]
I've avoided this as it really depends on the device and some implement entities with a binary sensor with a device class battery where the entity state is true when the battery is ok (so reversing the logic).
Since entity id's can be translated and/or renamed this can't be detected automatically with any consistency.

**Comment by peterwup** [comment]
Just for curiosity: I thought you use the device class instead of the name of an entity. So it means if a device has another name as `sensor.<devicename>_battery` you will not finde the anlog value too ? 

Concerning the logic of the "BinarySensorDeviceClass.BATTERY" the HASS spec defines it: "battery: on means low, off means normal" and I would hope/expect that moste devices used at in this way but I think you have more pracitacal experiences as me, I just have EQ3 homematic components with "BinarySensorDeviceClass.BATTERY" only.

**Comment by andrew-codechimp** [comment]
I do check the device class, sorry I was revisiting old thoughts on how this could have been approached and thought I'd mention why I don't check the entity id to head off that one.

That documentation is interesting, I'd never seen it defined as explicitly as that, which means all core integrations at least would abide by it, and hopefully most custom ones, I've seen some bad device classes not related to batteries elsewhere and they are fairly easy to fix if you have a good maintainer.

I think I could make that work, if it is used badly the custom template could always override it, I'll investigate.

**Reply by peterwup** [reply]
Thank you for thinking about it.

**Comment by andrew-codechimp** [comment]
I have just pre-released a version 2.8.1 which includes this, along with attributes on the battery_low_plus entity.
If you would like to test it you can get the pre-release via HACS by following these instructions
https://andrew-codechimp.github.io/HA-Battery-Notes/faq/#how-do-i-install-pre-release-versions-via-hacs

**Reply by peterwup** [reply]
I installed it, and it works like expected. 
<img width="383" alt="Screenshot 2025-01-05 155113" src="https://github.com/user-attachments/assets/819f9aa9-bd59-421d-b56a-83ee82970db9" />

I got the status of all batteries and the info which one I need to replace:

````
type: custom:battery-state-card
title: Batterie zustand
secondary_info: "{attributes.battery_type_and_quantity}"
round: 0
filter:
  include:
    - name: entity_id
      value: "*_battery_plus"
    - name: entity_id
      value: "*_battery_plus_low"
  exclude:
    - name: state
      value: Unknown
    - name: state
      value: Unavailable
bulk_rename:
  - from: Batterie+
  - from: Batteriestand
  - from: Low Battery
  - from: Akku fast leer
state_map:
  - from: "off"
    to: 100%
  - from: "on"
    to: 10%
collapse: 10
sort:
  - state

````
Thank you very much.
