### DISCUSSION TITLE
battery-state-card and battery_type_and_quantity as secondary_info

### DISCUSSION THREAD

**Discussion by WernerModenbach** [andrew-codechimp/HA-Battery-Notes#2596] [Q&A]
Hi!
I have some battery devices integrated by Homematic(IP) Local.
I added them to Battery-Notes and I can copy and show the entities on my dashboard.
When using a battery-state-card I'm not able to show the battery type as the second_info.
Just nothing is displayed.
I think I followed the example given. Thanks for any help and hints.
Here is my card definition:

`type: custom:battery-state-card
secondary_info: "{attributes.battery_type_and_quantity}"
round: 0
collapse: 5
filter:
  include:
    - name: entity_id
      value: "*_battery_plus*"
  exclude:
    - name: attributes.battery_low
      value: false
sort:
  by: state
  desc: false
state_map:
  - from: "off"
    to: 80
  - from: "on"
    to: 10
bulk_rename:
  - from: " Akku fast leer"
  - from: " Batterie"
  - from: " Battery"
  - from: " level"
colors:
  steps:
    - "#ff0000"
    - "#ffff00"
    - "#00ff00"
  gradient: true`

**Comment by andrew-codechimp** [comment]
That looks very similar to what I have working, try this simpler example and check your indents.
Also force a browser refresh as I've seen odd things at times with some cards.

```
type: custom:battery-state-card
title: Battery Warnings
round: 0
secondary_info: "{attributes.battery_type_and_quantity}"
filter:
  include:
    - name: entity_id
      value: "*_battery_plus"
  exclude:
    - name: attributes.battery_low
      value: "false"
bulk_rename:
  - from: Battery+
sort:
  - state

```
