### DISCUSSION TITLE
"*_battery_plus_low"  + secondary info

### DISCUSSION THREAD

**Discussion by peterwup** [andrew-codechimp/HA-Battery-Notes#2597] [Q&A]
I have several devices where only a BinarySensorDeviceClass.BATTERY is available. 
I added a template to all this devices and now each device has the  "*_battery_plus_low" entity. 
So far so good. 
For the visualisation I used battery-state-card:
````
type: custom:battery-state-card
secondary_info: "{attributes.battery_type_and_quantity}"
round: 0
filter:
  include:
    - name: entity_id
      value: "*_battery_plus"
    - name: entity_id
      value: "*_battery_plus_low"      
  exclude:
    - name: state
      value: "Off"
    - name: state
      value: Unknown
    - name: state
      value: Unavailable
    - name: state
      value: 40
      operator: ">"
bulk_rename:
  - from: "Batterie+"
  - from: "Akku fast leer"
state_map:
  - from: 'off'
    to: 100%
  - from: 'on'
    to: 10% 
sort:
  - state
 
````

![Screenshot 2025-01-03 170257](https://github.com/user-attachments/assets/2a54620a-4069-425b-b976-aad6dda89231)

Now I have one nice overview with all devices inside. Only drawback: 
"*_battery_plus_low"   seems not to have the nice atribute **battery_type_and_quantity** (see entity _GaragentorPos_). 
Any idea how I can manage to get this infos in the overview ? This was my main target for the overview.
