### DISCUSSION TITLE
New sensor: low_battery_level_threshold

### DISCUSSION THREAD

**Discussion by danielbrunt57** [andrew-codechimp/HA-Battery-Notes#507] [Ideas]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

It would be nice to have individual "low-battery" threshold values stored for each device to trigger low-battery notifications .  I've not found a low-battery battery notification package or blueprint which addresses how different devices (like my front door lock) do not work well below 75%, others might work okay down to 40% while some may go as low as 20% or lower and still function.

### Describe the solution you'd like

Create an additional sensor to store a low-battery level threshold value (%) for the device along with a service to be able to set/change the value, like the one for battery replaced date.
![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/49846893/63c6dbbb-ea1a-488a-920a-defa1c0bf10f)

### Describe alternatives you've considered

Digging inside existing solutions to hard-code exceptions for the low-battery alert threshold.

### Additional context

Perhaps also consider adding an additional `true|false` sensor which becomes `true` when `battery_level` < `low_battery_threshold`.
Once a low-battery level threshold sensor exists, users could create templated helpers but having the integration do that itself would be useful!

**Comment by andrew-codechimp** [comment]
I like this idea and something else I'm working on at the moment will tie in well to this.
I'll just have to consider how a default threshold will work.

Moving it to discussion/ideas where I keep longer term features.

**Reply by danielbrunt57** [reply]
For me, I'd be happy with just an automatically created sensor (or attribute) to store a low battery level trigger value, the initial default value of which is a user configurable system default (20%?) which can be overridden in configuration.yaml and is then prefilled at sensor creation time with the ability for the user to alter before creating a new sensor. Afterwards, a service call/button press can change it like how date works now.

**Comment by danielbrunt57** [comment]
What about a single sensor like:
```
sensor.south_patio_blind_battery_information:
  state: <battery_type>
  attributes:
    last_changed: <user_entered_date>
    low_battery_threshold: <default = <system_default=20|configured_default> >
    low_battery: <true|false>  <<-- set by (if possible) whether (battery_level < low_battery_threshold)
```
