### ISSUE TITLE
Add new attribute: battery_last_updated_button

### ISSUE THREAD

**Issue by danielbrunt57** [andrew-codechimp/HA-Battery-Notes#1032]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

Having this info as an attribute of the Battery+ sensor would simplify referencing the button entity to update the associated battery's battery_last_replaced date. Rather than having to resort to templating like:
`{{ entity_id | replace("sensor.","button.")|replace("_battery_plus","_battery_replaced") }}`
one could use a more elegant and straightforward `{{ state_attr(entity_id, 'battery_last_replaced_button') }}` template.

### Describe the solution you'd like

I tried adding a templated attribute via custom-ui but it is not completely real i.e. It's available in the front-end (custom:battery-state-card) but not the back-end (scripting/dev tools):
```
state_class: measurement
battery_quantity: 1
battery_type: CR2032
battery_type_and_quantity: CR2032
battery_low: false
battery_low_threshold: 15
battery_last_reported: "2024-02-14T07:01:08.891694"
battery_last_reported_level: "50"
battery_last_replaced: "2024-02-14T07:49:11.536876+00:00"
unit_of_measurement: "%"
device_class: battery
friendly_name: Outside Weather
hide_attributes:
  - templates
templates:
  icon_color: >
    var r = Math.min(255, Math.round(510 - 5.10 * Number(state))); var g =
    Math.min(255, Math.round(5.10 * Number(state))); var h = r * 0x10000 + g *
    0x100; return '#' + ('000000' + h.toString(16)).slice(-6);
  battery_last_replaced_button: >
    return 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0]
    + '_battery_replaced';
icon_color: "#ffff00"
battery_last_replaced_button: button.outside_weather_battery_replaced
```

### Describe alternatives you've considered

Too many to mention!

### Additional context

```
homeassistant:

  customize_glob:
    "*.*":
      hide_attributes:
        - templates
        
    sensor.*_battery:
      templates: &battery_color
        icon_color: >
            var r = Math.min(255, Math.round(510 - 5.10 * Number(state)));
            var g = Math.min(255, Math.round(5.10 * Number(state)));
            var h = r * 0x10000 + g * 0x100;
            return '#' + ('000000' + h.toString(16)).slice(-6);

    sensor.*_battery_level:
      templates: *battery_color

    sensor.*_battery_plus:
      templates: 
        <<: *battery_color
        battery_last_replaced_button: >
          return 'button.' + entity.entity_id.split('.')[1].split('_battery_plus')[0] + '_battery_replaced';
```

**Comment by andrew-codechimp** [comment]
Why do you need to access the button when you could make a service call which just requires a device_id that's already supplied in the attributes?
https://andrew-codechimp.github.io/HA-Battery-Notes/services/#battery_notesset_battery_replaced

**Comment by danielbrunt57** [comment]
Um, I was overthinking it? Plus, I was not aware of the `service: battery_notes.set_battery_replaced` using device_id.
That simplifies my config in `custom:auto-entities` with `custom: battery-state-card` to achieve a tap_action to update the battery_replaced_date.  I still have to call a script but the script is simpler now.
```
alias: Battery Notes - Update Battery Replaced Date
description: Updates the battery last replaced date
fields:
  entity_id:
    name: entity_id
    description: Battery Entity ID
    example: "sensor.outside_weather_battery_plus"
sequence:
  - service: battery_notes.set_battery_replaced
    data: 
      device_id: "{{ device_id(entity_id) }}"
```
```
type: custom:auto-entities
card:
  type: custom:battery-state-card
  title: Low Batteries
  debug: false
  card_mod:
    class: inline-card
filter:
  include:
    - integration: battery_notes
      domain: sensor
      attributes:
        device_class: battery
      state: < 60
      options:
        name: '{attributes.friendly_name} ({attributes.battery_type_and_quantity})'
        secondary_info: 'Last reported: {attributes.battery_last_replaced_button}'
        tap_action:
          action: call-service
          service: script.battery_notes_battery_replaced
          service_data:
            entity_id: this.entity_id
    - integration: battery_notes
      domain: binary_sensor
      attributes:
        device_class: battery
      state: 'on'
  exclude:
    - integration: mobile_app
sort:
  method: state
  numeric: true
```
I've requested an enhancement to battery-state-card and @maxwroc marked as a v3.3 milestone:
[Modify tap_action + add hold_action & double_tap_action as per Home Assistant Dashboard Actions for tap actions #691](https://github.com/maxwroc/battery-state-card/issues/691).  
If he also adds his KString parsing to the entity_id in tap_action then I would be able to reference the new attribute via '{attributes.battery_last_replaced_button}' and avoid the sctipt.

**Comment by andrew-codechimp** [comment]
Working out the button entity_id from the battery+ sensor is a lot of messy code hops I'd rather avoid, especially if someone goes and gives it a different entity_id.
Hopefully using the service with the script will suffice?

**Comment by maxwroc** [comment]
I think that the tap_action (or even hold_action, and other standard actions) are not a perfect solution for resetting "battery replaced date". 

FYI I plan to add features in battery-state-card which will be battery-notes specific. In particular I was thinking about adding a button(s) for standard actions available in battery-notes (e.g. "battery replaced", "changing battery type" etc) So hopefully you won't have to struggle to achieve what you want.

I will allow KString usage in various other places too so you should be able to do it one way or the other

**Comment by andrew-codechimp** [comment]
@maxwroc if you need any clarification on how things work in Battery Notes or would like small changes happy to discuss.
There's a discussion forum on this repo you can start a general discussion on if you want and just @ me

**Comment by webmogul1** [comment]
`  tap_action:
    action: call-service
    confirmation:
      text: Battery Replaced?
    service: script.battery_notes_battery_replaced
    service_data:
      entity_id: this.entity_id`

**Comment by webmogul1** [comment]
`  hold_action:
    action: call-service
    confirmation:
      text: Battery Replaced?
    service: script.battery_notes_battery_replaced
    service_data:
      entity_id: this.entity_id
`

**Comment by webmogul1** [comment]
@danielbrunt57 

```
  tap_action:
    action: call-service
    confirmation:
      text: Battery Replaced?
    service: script.battery_notes_battery_replaced
    service_data:
      entity_id: this.entity_id

```
