### ISSUE TITLE
Feature Request: Automatically add battery percentage for voltage-only batteries

### ISSUE THREAD

**Issue by zacs** [andrew-codechimp/HA-Battery-Notes#1579]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

It is frustrating to have devices that give you a battery's voltage, but not a percentage. For most people, the voltage means nothing. 

### Describe the solution you'd like

It would be nice if a complementary entity was created and linked to the device, which used a percentage unit of measure. 

Percentage could be based on the historical range of voltages for the devices, which would be a pretty deep implementation. An easier solution might be that during the Battery Notes setup for this entity, the user was prompted for the lower and upper bounds of the expected voltage. 

### Describe alternatives you've considered

The alternative that I use currently is to just create a template sensor for the percentage. I do this like so (this is for my Weatherflow Tempest weather station, just as an example): 

```
template:
  - sensor:
    - name: "ST-00084698 Battery Battery Level" 
      # Formula: (($volt - $low) / ($high - $low)) * 100
      # Currently observed max: 2.82
      # Denominator is 2.82-2.11=0.0071 (including the *.01)
      unique_id: "st_00084698_battery_level"
      state: >-
        {% set voltage = states('sensor.st_00084698_battery_voltage') | float(0) %}
        {{ ((voltage - 2.11) / 0.0071) | int }}
      device_class: battery
      unit_of_measurement: '%'

```

However, this is not ideal because:
1. It's a lot of repetitive YAML
2. The template sensor isn't linked to the device in the UI, which would be pretty useful

### Additional context

Here is an example of the generally useless battery values in the Ecowitt integration (just for example). Are these values actionable? No! 

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/27705/daf25838-31c0-477f-9084-b9dd0cb8a3b6)
