### ISSUE TITLE
Cannot set last_changed date via service

### ISSUE THREAD

**Issue by chemelli74** [andrew-codechimp/HA-Battery-Notes#1801]
## System Information

version | core-2024.6.4
-- | --
installation_type | Home Assistant Container
dev | false
hassio | false
docker | true
user | root
virtualenv | false
python_version | 3.12.2
os_name | Linux
os_version | 4.4.302+
arch | x86_64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4989
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 22

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 12
views | 14
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 19 giugno 2024 alle ore 19:53
-- | --
current_recorder_run | 28 giugno 2024 alle ore 19:17
estimated_db_size | 972.75 MiB
database_engine | sqlite
database_version | 3.44.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Cannot set the last replace data via service.
Call details:

```
service: battery_notes.set_battery_replaced
data:
  source_entity_id: sensor.sensore_1_cameretta_battery_last_replaced
  datetime_replaced: "2024-06-28 12:27:00"
  device_id: deef0ff3cb2886ea4b319d38fe6270c8
```

Device:

![image](https://github.com/andrew-codechimp/HA-Battery-Notes/assets/57354320/b26104ec-c37e-42bf-a64d-f8924aeb06e5)

### Reproduction steps

1. configure device in battery notes
2. hit button "replace battery"
3. check value: all fine so far
4. call "battery_notes.set_battery_replaced"
5. check value: is still the old one
6. check log: error reported

### Debug logs

```text
2024-06-29 16:12:39.480 ERROR (MainThread) [custom_components.battery_notes] Entity sensor.sensore_1_cameretta_battery_last_replaced not configured in Battery Notes
```

**Comment by andrew-codechimp** [comment]
source_entity_id is only used if you created an entity type battery note and should be set to the entity_id that battery notes is associated with.
If your battery note is a more typical device type then setting the  source_entity_id: "" should fix this.

service: battery_notes.set_battery_replaced
data:
  source_entity_id: sensor.sensore_1_cameretta_battery_last_replaced
  datetime_replaced: "2024-06-28 12:27:00"
  device_id: deef0ff3cb2886ea4b319d38fe6270c8

**Comment by chemelli74** [comment]
Confirmed to work fine with:

```
service: battery_notes.set_battery_replaced
data:
  datetime_replaced: "2024-06-28 12:27:00"
  device_id: deef0ff3cb2886ea4b319d38fe6270c8
```

Thank you !

I suggest you give a failure feedback to the UI when the settings are wrong.
And improve the service description to help others.
