### ISSUE TITLE
Raise an event when battery replaced

### ISSUE THREAD

**Issue by andrew-codechimp** [andrew-codechimp/HA-Battery-Notes#2247]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3Aenhancement).

### Is your feature request related to a problem? Please describe.

I want to know when I use a battery. 

### Describe the solution you'd like

When the battery replaced button or action are called raise an event with details of the device/battery so that it can be used for shopping lists etc. 

### Describe alternatives you've considered

None

### Additional context

None

**Comment by FragMenthor** [comment]
Thank you for considering this 🙏

**Comment by andrew-codechimp** [comment]
It's coming soon, just a bit of testing to do.

**Comment by FragMenthor** [comment]
Thank you! Already on your beta, tested and IT WORKS exactly as I intended! 😀 Thanks!!!

**Comment by FragMenthor** [comment]
Here is my personal automation: 

```
alias: "Pilhas: Atualizar stock"
description: Atualizar stock de pilhas ao serem usadas
triggers:
  - event_type: battery_notes_battery_replaced
    trigger: event
conditions: []
actions:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.battery_type == 'CR2450' }}"
        sequence:
          - action: input_number.decrement
            metadata: {}
            data:
              amount: |
                {{ trigger.event.data.battery_quantity | int }}
            target:
              entity_id: input_number.pilhas_cr2450_stock
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.battery_type == 'CR2430' }}"
        sequence:
          - action: input_number.decrement
            metadata: {}
            data:
              amount: |
                {{ trigger.event.data.battery_quantity | int }}
            target:
              entity_id: input_number.pilhas_cr2430_stock
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.battery_type == 'CR2032' }}"
        sequence:
          - action: input_number.decrement
            metadata: {}
            data:
              amount: |
                {{ trigger.event.data.battery_quantity | int }}
            target:
              entity_id: input_number.pilhas_cr2032_stock
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.battery_type == 'AA' }}"
        sequence:
          - action: input_number.decrement
            metadata: {}
            data:
              amount: |
                {{ trigger.event.data.battery_quantity | int }}
            target:
              entity_id: input_number.pilhas_aa_stock
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.battery_type == 'AAA' }}"
        sequence:
          - action: input_number.decrement
            metadata: {}
            data:
              amount: |
                {{ trigger.event.data.battery_quantity | int }}
            target:
              entity_id: input_number.pilhas_aaa_stock
mode: queued
max: 5
```

**Comment by andrew-codechimp** [comment]
You were very keen to get this then 😄 
Glad it's working and thanks for testing, I'll keep this in beta for a week or so but fingers crossed no issues.

**Comment by FragMenthor** [comment]
> You were very keen to get this then 😄 Glad it's working and thanks for testing, I'll keep this in beta for a week or so but fingers crossed no issues.

I think this will work best, in my case:
```
alias: "Pilhas: Atualizar stock"
description: Atualizar stock de pilhas ao serem usadas
triggers:
  - event_type: battery_notes_battery_replaced
    trigger: event
conditions: []
actions:
  - action: input_number.decrement
    metadata: {}
    data:
      amount: |
        {{ trigger.event.data.battery_quantity | int }}
    target:
      entity_id: |
        input_number.pilhas_{{ trigger.event.data.battery_type | lower }}_stock
```
