### ISSUE TITLE
Trigger not working

### ISSUE THREAD

**Issue by hellcry37** [andrew-codechimp/HA-Battery-Notes#796]
### System Health details

This does not appear for HA container version for some time now

### Checklist

- [X] I have added `battery_notes:` to my configuration.yaml and restarted.
- [X] I have read the [FAQ's](https://andrew-codechimp.github.io/HA-Battery-Notes/faq).
- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/andrew-codechimp/ha-battery-notes/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

I replaced 2 battery's on some sensors and this event "battery_notes_battery_increased" never fired.
Maybe I am doing something wrong or my config is bad?

```yaml
- id: 'battery_replaced'
  alias: Battery - Replaced
  description: 'Set battery as replaced when battery level increase by 45%+'
  mode: queued
  trigger:
    - platform: event
      event_type: battery_notes_battery_increased
  condition: []
  action:
    - service: battery_notes.set_battery_replaced
      data:
        device_id: "{{ trigger.event.data.device_id }}"
    - alias: Notify ciprian on telegram
      service: script.turn_on
      target:
        entity_id: script.notification_telegram_ciprian
      data:
        variables:
          title_message_to_send: "{{ trigger.event.data.device_name }} Battery Replaced"
          text_message_to_send: >
            Device battery level is now {{ trigger.event.data.battery_level }}%
```

configuration.yaml
```yaml
battery_notes:
  enable_autodiscovery: true
  show_all_devices: false
  enable_replaced: true
  default_battery_low_threshold: 25
  battery_increase_threshold: 45
  hide_battery: true
  round_battery: true
```

### Reproduction steps

1. battery low notification was issued by automation with a battery level of 0%
2. replaced battery
3. new battery level is 100% but event battery_notes_battery_increased never fired even if battery went from 0% to 100% > 45%

I am guessing event never fired since automation never triggered.

This happen twice on two different occasions 2 different sensors
...

### Debug logs

```text
Unfortunate I do not have this. I need to get a low battery to test more.
```
